### ISSUE TITLE
multiprocessing issue

### ISSUE THREAD

**Issue by lucaz88** [antismash/antismash#237] opened 2020-02-14 09:55 UTC
Hi, 
I am doing a full-featured run of antismash 5.1 on a bacterial high-quality genome. I run the following command:

`antismash -c 60 --fullhmmer --cf-create-clusters --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees --output-dir 3_secondary_metab/C08 C08.gbk`

and get repeatedly this warning:

`Process ForkPoolWorker-141:
Traceback (most recent call last):
  File "/project02/miniconda3/envs/antismash/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/project02/miniconda3/envs/antismash/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/project02/miniconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/project02/miniconda3/envs/antismash/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "/project02/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/secmet/qualifiers/nrps_pks.py", line 103, in extend
    raise NotImplementedError("Extending this list won't work")
NotImplementedError: Extending this list won't work
`

It doesn't kill the execution of the routine but the job never finish and there is no CPU usage after the last occurrence of the error.
I am using a recent conda installation of antismash on a Linux Mint 19.2

**Comment by kblin** [comment] 2020-02-19 09:33
While I can reproduce the issue, I can only reproduce it within a conda environment, not on a plain non-conda install. This hints that this is something conda-related.

**Comment by kblin** [comment] 2020-02-19 09:42
The issue is related to the `--smcogs-trees` option.

Minimal reproducer:

```bash
wget https://dl.secondarymetabolites.org/testing/balh.embl
antismash -d --cpus 2 --smcog-trees balh.embl
```

**Comment by SJShaw** [comment] 2020-02-19 14:32
If anyone knows what conda changes (and hopefully where) in the multiprocessing package or other standard packages, that would be useful.

**Comment by tamuanand** [comment] 2020-03-07 18:21
hello @SJShaw - I see that you have a pull request related to the multiprocessing issue - once it is fixed, will the fix be available via BioConda or should one download the tarball and do a pip install.

Thanks for looking into this multiprocessing issue.

**Comment by SJShaw** [comment] 2020-03-09 14:45
Once 5.1.2 is released and once bioconda updates the antiSMASH package to the new version, it will be available via bioconda.

If you're using a git clone, you can do a `git pull` the moment it's merged. If you're using a release tarball, you'll need to wait for the 5.1.2 release, but won't have to wait for bioconda.

**Closed** 2020-03-11 13:28 UTC
Labels: conda
