### ISSUE TITLE
Plans to add py3 port to bioconda?

### ISSUE THREAD

**Issue by nick-youngblut** [antismash/antismash#196] opened 2019-09-10 18:55 UTC
Are you planning on adding this py3 port of antismash to bioconda? [The current version on bioconda is 4.2](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/antismash/meta.yaml).

**Comment by SJShaw** [comment] 2019-09-19 16:20
It is in our list of things to do, but we haven't yet got to it. I don't use bioconda myself, so I tend to forget it exists.

**Comment by nick-youngblut** [comment] 2019-09-19 17:07
The v5 recipe is [already in the works](https://github.com/bioconda/bioconda-recipes/pull/17382), but it's still waiting on @kblin. I definitely recommend conda, since it really helps for creating & maintaining reproducible bioinformatics environments, something that is still extremely lacking in the field.

**Comment by SJShaw** [comment] 2019-09-20 11:28
We build docker containers for antiSMASH for reproducibility, as conda has given us problems in various ways before. You seem to have come across in the bioconda recipe linked.

Since the recipe is already being worked on, should we now closed this issue?

**Closed** 2019-09-20 11:51 UTC
