### ISSUE TITLE
RuntimeError: unexpected output from hmmpfam2: /home/cheyanlin/miniconda3/envs/antismash/bin/hmmpfam2, check path

### ISSUE THREAD

**Issue by cylcheyanlin** [antismash/antismash#435] opened 2022-04-02 02:34 UTC
**Describe the bug**
Dear everyone,
I install the antismash-6-1-0 with the followed condes:
$ conda create -n antismash
$ conda activate antismash

$ conda install -y diamond=0.8.36
$ conda install -y fasttree=2.1.9
$ conda install -y glimmerhmm=3.0.4
$ conda install -y hmmer=2.3.2
$ conda install -y hmmer=3.1b2
$ conda install -y meme=4.11.2
$ conda install -y muscle=3.8.1551
$ conda install -y blast=2.2.31
$ conda install -y prodigal=2.6.3
$ conda install -y java-jdk
$ conda install -y python

$ wget https://dl.secondarymetabolites.org/releases/6.1.0/antismash-6.1.0.tar.gz
$ tar -zxf antismash-6.1.0.tar.gz
$ pip install ./antismash-6.1.0.

$ download-antismash-databases

When I install the hmmer3.1b2 using conda, it reported the error :
ERROR 02/04 09:44:05 antismash.modules.active_site_finder: preqrequisite failure: Failed to locate file: 'hmmpfam2'
ERROR 02/04 09:44:05 antismash.modules.lanthipeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
ERROR 02/04 09:44:05 antismash.modules.lassopeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
ERROR 02/04 09:44:05 antismash.modules.sactipeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
ERROR 02/04 09:44:05 antismash.modules.thiopeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
Some module prerequisites not satisfied.

I uninstalled the hmmer=3.1b2 and got the other error:
Traceback (most recent call last):
File "/home/cheyanlin/miniconda3/envs/antismash/bin/antismash", line 8, in
sys.exit(entrypoint())
File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 125, in entrypoint
sys.exit(main(sys.argv[1:]))
File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 113, in main
antismash.run_antismash(sequence, options)
File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 673, in run_antismash
result = _run_antismash(sequence_file, options)
File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 680, in _run_antismash
_log_found_executables(options)
File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 775, in _log_found_executables
version = " ({})".format(version_getter()) # pylint: disable=not-callable
File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/common/subprocessing/hmmpfam.py", line 72, in run_hmmpfam2_version
version_line = run_hmmpfam2_help().split('\n')[1]
File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/common/subprocessing/hmmpfam.py", line 65, in run_hmmpfam2_help
raise RuntimeError(msg % hmmpfam2)
RuntimeError: unexpected output from hmmpfam2: /home/cheyanlin/miniconda3/envs/antismash/bin/hmmpfam2, check path

Also, when I install the hmmer=2.3.2, it showed that 
![image](https://user-images.githubusercontent.com/95027351/161362343-05d57e68-4c6a-4eb3-a883-1009217a09d9.png)
Is this true?

So I want to understand this problem and how to solve this error. Could you give me a hand? Thank you very much.

**Comment by kblin** [comment] 2022-04-04 09:45
You need both a hmmer2 and a hmmer3 install to run antiSMASH. See the description at https://docs.antismash.secondarymetabolites.org/install/#dependencies-via-bioconda

**Comment by kblin** [comment] 2022-04-04 09:46
Oh, now I noticed what the problem is with your package list. The hmmer2 install that can be installed in parallel to hmmer3 is called `hmmer2`.

**Comment by Xiao-qiang-wang** [comment] 2022-05-19 05:24
> Oh, now I noticed what the problem is with your package list. The hmmer2 install that can be installed in parallel to hmmer3 is called `hmmer2`.

What does the mean 'The hmmer2 install that can be installed in parallel to hmmer3 is called `hmmer2`.?

**Comment by SJShaw** [comment] 2022-05-19 16:55
Use `conda install hmmer2` instead of `conda install hmmer=2.3.2`.

**Comment by RobTour** [comment] 2022-08-16 21:37
Hello - new user.  I am getting a similar error when executing `antismash --check-reqs`  except for muscle.  
I am on a Windows 10 OS, WSL2 running Ubuntu-20.04 
I installed antismash-6.1.1 using instructions from the help page.  (FYI bioconda installer wouldn't work for me)

$ conda create -n antismash
$ conda activate antismash
$ conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm

$ wget https://dl.secondarymetabolites.org/releases/6.1.1/antismash-6.1.1.tar.gz
$ tar -zxf antismash-6.1.1.tar.gz

$ pip install ./antismash-6.1.1
$ download-antismash-databases

All seemed to work correctly.  However, when I executed:

$ antismash --check-prereqs 

I returns the following:  

Traceback (most recent call last):
  File "/home/tournay/.local/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/tournay/.local/lib/python3.8/site-packages/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/tournay/.local/lib/python3.8/site-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/home/tournay/.local/lib/python3.8/site-packages/antismash/main.py", line 674, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/tournay/.local/lib/python3.8/site-packages/antismash/main.py", line 681, in _run_antismash
    _log_found_executables(options)
  File "/home/tournay/.local/lib/python3.8/site-packages/antismash/main.py", line 776, in _log_found_executables
    version = " ({})".format(version_getter())  # pylint: disable=not-callable
  File "/home/tournay/.local/lib/python3.8/site-packages/antismash/common/subprocessing/muscle.py", line 55, in run_muscle_version
    raise RuntimeError(msg % muscle)
RuntimeError: unexpected output from muscle: /home/tournay/miniconda3/envs/antismash/bin/muscle, check path

thx - robt

**Comment by RobTour** [comment] 2022-08-17 00:04
I resolved this by rolling a back to muscle v 3.8.1551
`conda update` installed the v5 version of muscle 

I also had to manually install meme and java-jdk

**Comment by jlli6t** [comment] 2022-08-17 00:08
> hmmer2

Have you installed muscle? If so, check the name and path of muscle.  The program only regconize "muscle" instead of "muscle3.8.31_i86***" stuff.

**Comment by jlli6t** [comment] 2022-08-17 00:20
> I resolved this by rolling a back to muscle v 3.8.1551 `conda update` installed the v5 version of muscle
> 
> I also had to manually install meme and java-jdk

Have you installed muscle? If so, check the name and path of muscle. The program only regconize "muscle" instead of "muscle3.8.31_i86***" stuff.

**Comment by RobTour** [comment] 2022-08-17 12:58
Yes - it wasn't a path and name issue, but a version issue.  It was fixed by rolling back to a supported version of muscle.

**Closed** 2022-10-14 14:37 UTC
