### ISSUE TITLE
antiSMASH failing on duplicated CDS Names

### ISSUE THREAD

**Issue by standage** [antismash/antismash#321] opened 2020-11-19 19:58 UTC
Tools like Prokka and DFAST will sometimes give the same `Name` to distinct CDS features, if related or duplicated genes are present in the same genome. The GFF3 specification allows for this: only `ID` features need to be unique.

But when I run antiSMASH using these GFF3 files for `--genefinding-gff3` arguments, I get the following error.

> ERROR    13/11 15:47:28   multiple CDS features have the same name for mapping: GldE

This error occurs even when the CDS features have distinct IDs.

I don't know whether this is intended behavior, but it puts an extra burden on the user to preprocess their data and make sure that each CDS Name is unique.

**Comment by SJShaw** [comment] 2020-11-23 10:56
This is intended behaviour.

All CDS features are expected to have a unique identifier within a record/contig. This makes referring to a particular CDS in the results (both HTML and Genbank) much easier to manage, as there's no ambiguity about which particular feature is being referred to.

You are correct that GFF doesn't require the alternate naming fields to be unique per file, but part of that is to allow for sensible names to show users (e.g. the `name` field is intended to be the name shown to users, which is why we override the ID with that name when present).

Is your duplication of names due to those affected CDS features being splice variants?

**Comment by standage** [comment] 2020-11-24 18:32
Thanks for the response @SJShaw! This is a bacterial genome, so no alternative splicing. It turns out that the duplicated names were not derived from Prokka or DFAST annotation, as I had originally suspected. It was fairly easy for me to fix this particular case.

But in general, I still worry that antiSMASH is (ab)using the `Name` attribute to do the job that `ID` was designed to solve. The `Name` is explicitly about human readability, and the `ID` is about unique feature identification.

I'm sympathetic that the GFF3 files seen out in the wild differ a whole lot in their content and structure, and that it's often necessary to impose constraints beyond the GFF3 spec to make data handling feasible. I guess, consider this a suggestion that you consider using the `ID` for mapping and the `Name` for display purposes.

**Comment by zdk123** [comment] 2021-12-02 17:08
Just adding 2cents is that I've seen failures on this type directly on NCBI genbanks.

E.g. there are two CDSs with the locus_tag "QR97_26480" in this nucleotide:
https://www.ncbi.nlm.nih.gov/nuccore/CP011799.1

Would this case be fixed by PR #385?

**Comment by SJShaw** [comment] 2021-12-02 20:12
That particular case is fixed by that PR, yes. There will still be other cases where duplicated names will cause issues, especially if the annotation pipeline that creates the CDS features doesn't annotate the parent genes for splice variants.

**Closed** 2023-03-15 12:27 UTC
