### ISSUE TITLE
Multiple CDS features have the same name for mapping, but unable to find offending CDS. 

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#354] opened 2021-04-09 10:25 UTC
I am running fungiSMASH in browser as i want to utilise the v6 beta but when submitting a genbank files I get the following error: ` ERROR 09/04 09:59:18 multiple CDS features have the same name for mapping: cds804716_804887`

However when greping into the genbank file the string `cds804716_804887` does not exist anywhere.

If it matters the genbank files are converted Braker2 `.gtf` annotations using this [script](https://github.com/chapmanb/bcbb/blob/master/gff/Scripts/gff/gff_to_genbank.py)

I imagine the way in which the genbank files is created could have had something to do with it but I am still unable to even see the erroneous string within the genbank file

**Comment by SJShaw** [comment] 2021-04-09 11:32
If no identifier qualifiers are provided of  `gene`, `protein_id`, or `locus_tag`, an identifier is created as `CDS<start>_<end>`. I suspect you've got multiple CDS features with the location 804716-804887, of which at least two are missing those identifiers.

**Comment by Bollie15** [comment] 2021-04-12 03:42
> If no identifier qualifiers are provided of `gene`, `protein_id`, or `locus_tag`, an identifier is created as `CDS<start>_<end>`. I suspect you've got multiple CDS features with the location 804716-804887, of which at least two are missing those identifiers.

I have the same problem. Would you know how to solve this problem?
```shell
ERROR    12/04 11:31:09   multiple CDS features have the same name for mapping: LOC111350401
```
![Screenshot from 2021-04-12 11-39-15](https://user-images.githubusercontent.com/56813612/114337640-11b51300-9b84-11eb-9d9b-9f18d581b120.png)

**Comment by SJShaw** [comment] 2021-04-12 09:43
Your issue is different, you've specified two distinct CDSs with the same identifier. You can choose to rename one of them or add the `locus_tag` qualifier with unique values.

**Comment by Lamm-a** [comment] 2021-04-13 06:38
@SJShaw Would it be viable for the to write a script to add a generated identifier to solve this issue?

**Comment by SJShaw** [comment] 2021-04-23 15:11
A script to generate identifiers should work, as would just removing the duplicates, since the duplicate 
won't be adding any extra information.

I've never used Braker, so I'm unsure of what would be required to get a clean output, sorry.

**Comment by sunnycqcn** [comment] 2022-03-02 21:12
you can slove this problem if you run this command 
`agat_sp_keep_longest_isoform.pl --gff ${block}/update_results/Leptosphaeria_maculans_${block}.gff3 -o ${block}/antismash/${block}.gff3`
before you run antimash.

**Comment by jlv100** [comment] 2022-03-31 02:15
This is actually caused by the new crc32 hashing on locations. crc32 shouldn't be used for hashing.  We ran into a clash rather quickly with the following locations, which result in the exact same crc32 digests:

    >>> from zlib import crc32
    >>> checksum=crc32('[5206081:5207221](-)'.encode('utf-8'))
    >>> f"{checksum:x}"
    '6dea7c77'
    >>> checksum=crc32('[1964876:1965035](-)'.encode('utf-8'))
    >>> f"{checksum:x}"
    '6dea7c77'

See #434 for a fix

**Comment by kblin** [comment] 2022-03-31 05:32
Can you confirm that this still is an issue in the current master branch after e86d6432?

**Comment by SJShaw** [comment] 2022-04-05 15:10
Closing this as an input issue for the original question (duplicate CDS features with no identifiers and exact locations).

**Closed by SJShaw** 2022-04-05 15:10 UTC
