### ISSUE TITLE
 v5.1.2: antismash.modules.nrps_pks: preqrequisite failure: Failed to locate executable for 'java'

### ISSUE THREAD

**Issue by cmandreani** [antismash/antismash#404] opened 2021-11-25 20:04 UTC
Ubuntu 20.04
Python 3.8.10
antiSMASH 5.1.2 (dependencies installed via Debian instructions)
biopython 1.76

Bugs=
1. RuntimeError: Modules failing prerequisites
2. ValueError: Called find_genes, but genefinding disabled

`antismash --check-prereqs`
/home/user/as_env/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
ERROR    25/11 15:46:21   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'meme'
ERROR    25/11 15:46:21   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'fimo'
ERROR    25/11 15:46:21   antismash.modules.nrps_pks: preqrequisite failure: Failed to locate executable for 'java'
Some module prerequisites not satisfied

`sudo apt-get install java`
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package java

```
antismash 16_E7.fa --pfam2go --smcog-trees --output-dir ~/output_5.1.2_allFtOn --fullhmmer --clusterhmmer --cb-general --cb
-knownclusters --cb-subclusters --asf
```
/home/user/as_env/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
ERROR    25/11 16:04:51   antismash.modules.nrps_pks: preqrequisite failure: Failed to locate executable for 'java'
Traceback (most recent call last):
  File "/home/user/as_env/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/main.py", line 641, in _run_antismash
    check_prerequisites(options.all_enabled_modules, options)
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/main.py", line 553, in check_prerequisites
    raise RuntimeError("Modules failing prerequisites")
RuntimeError: Modules failing prerequisites

Any ideas where may I be failing?
Since I'm not using CASSIS I believe that java is the main issue. Hence I tried:

`sudo apt install default-jre`

But when rerunning the error changed to:

/home/user/as_env/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/common/record_processing.py", line 239, in ensure_cds_info
    genefinding(sequence, options)
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/detection/genefinding/__init__.py", line 89, in run_on_record
    raise ValueError("Called find_genes, but genefinding disabled")
ValueError: Called find_genes, but genefinding disabled
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/as_env/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/main.py", line 665, in _run_antismash
    results.records = record_processing.pre_process_sequences(results.records, options,
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/common/record_processing.py", line 388, in pre_process_sequences
    sequences = parallel_function(partial, ([sequence] for sequence in sequences))
  File "/home/user/as_env/lib/python3.8/site-packages/antismash/common/subprocessing/base.py", line 132, in parallel_function
    results = jobs.get(timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Called find_genes, but genefinding disabled

I read [here](https://github.com/antismash/antismash/releases) in 'detailed changes' the following:
> common: Fix the java version detection when _JAVA_OPTIONS are set

Should I downgrade java maybe? The one I installed is 11.0.11 2021-04-20, but couldn´t find any specifications in this matter. 

Thanks.

**Comment by SJShaw** [comment] 2021-11-25 20:41
`default-jre` is fine, there's other Debian/Ubuntu packages that can provide Java, but as long as it's available it's fine.

For the genefinding error, you're running on a FASTA input without specifying a genefinding tool, which is why you're seeing that 
In newer versions of antiSMASH, that message is more helpful, but basically you just need to add `--genefinding-tool prodigal`, assuming that's a non-metagenomic bacterial input (see `--help-showall` for more options).

**Comment by cmandreani** [comment] 2021-11-26 01:07
Thanks for such a quick response. Is Prodigal the default gene-finding tool when running antiSMASH webserver?

I added the command suggested but still retrieved an error. I reviewed the advanced options in `--help-showall` but since the message only said "Killed" couldn't recognise which of them could solve the issue.

` antismash 16_E7.fa --pfam2go --smcog-trees --output-dir ~/output_5.1.2_allFtOn --fullhmmer --clusterhmmer --cb-general --cb-knownclusters --cb-subclusters --asf --genefinding-tool prodigal`

/home/user/as_env/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
WARNING  25/11 21:59:14   Matplotlib is building the font cache; this may take a moment.
WARNING  25/11 21:59:14   Matplotlib is building the font cache; this may take a moment.
Killed

Any ideas?

Thanks again.
Constanza

**Comment by SJShaw** [comment] 2021-11-26 10:46
I'm fairly certain you ran out of memory and the operating system killed antiSMASH (and possibly other processes as well). Either way, it wasn't antiSMASH's fault, since `Killed` is when the operating system kills the process (either automatically or user request).

How much RAM do you have? Do you have swap disabled? What size is your input file?

If you run with `-d` to show debugging messages, it'll show you more messages after those (unless matplotlib really is the cause of the memory problem), but this won't solve the problem, only give you a better idea of what it's doing at the time it gets killed.

**Comment by cmandreani** [comment] 2021-11-26 13:56
Thanks very much! I'll try to search in that path to solve it. I run the `-d` option and it's killed right after loading databases for ClusterBlast, so it makes sense.
Is there a minimum of RAM required? Or a maximum size for the input file? 
Please don´t close this thread yet in case another question rises up.

**Comment by SJShaw** [comment] 2021-11-29 09:23
There's a previous comment of mine about memory [here](https://github.com/antismash/antismash/issues/396#issuecomment-951970878), however 3 Gb is almost certainly too small for running clusterblast on an input file on that size. If you can free up the remaining RAM, then that might be enough, depending on how many regions are detected and how many hits there are. 

Since this isn't really an issue with antiSMASH as it is, I'm going to close the issue. You can still keep asking questions in it, though, it doesn't have to be open for that.

**Closed by SJShaw** 2021-11-29 09:23 UTC
