### ISSUE TITLE
Warning from conda install.

### ISSUE THREAD

**Issue by Lamm-a** [antismash/antismash#234] opened 2020-02-11 10:37 UTC
Thank you very much for your efforts in getting antiSMASH v5 onto bioconda.

When running the new antismash via conda however, I am getting this warning message indicating errors that I will assume happen in the future?:

```
/home/lamma/miniconda3/envs/antismash_v5/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/home/lamma/miniconda3/envs/antismash_v5/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
```

**Comment by SJShaw** [comment] 2020-02-11 16:13
Yes, these are warnings about things that might change in the future for two of our python dependencies, `sklearn` and `pyScss`.

`sklearn` 0.23 hasn't yet been released, so that's not an issue yet.
`pyScss` and its use of regex that causes the FutureWarning seems to still be completely functional, so we're not too worried. There's already an issue and matching pull request for `pyScss`, and whenever that is released and the package updated, the warning will go away.

**Comment by nick-youngblut** [comment] 2020-03-21 11:52
I see your warning and raise you an error:

```
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::antismash-5.1.1-py_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-5.1.1-py_0
location of failed script: /ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: /ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/lib/python3.7/site-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/lib/python3.7/site-packages/antismash/modules/lanthipeptides/__init__.py", line 13, in <module>
    from antismash.common.external.rodeo_svm.rebuild import pickle_classifier
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 9, in <module>
    from .svm_classify import save_classifier
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/TEST/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 76, in <module>
    sklearn_int_versions = list(map(int, sklearn.__version__.split('.')))
ValueError: invalid literal for int() with base 10: 'post1'

return code: 1

()
```

Conda info:
```
        active environment : base
    active env location : /ebio/abt3_projects/software/dev/miniconda3_dev
            shell level : 1
       user config file : /ebio/abt3/nyoungblut/.condarc
 populated config files : /ebio/abt3/nyoungblut/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.27
       base environment : /ebio/abt3_projects/software/dev/miniconda3_dev  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/leylabmpi/linux-64
                          https://conda.anaconda.org/leylabmpi/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/qiime2/linux-64
                          https://conda.anaconda.org/qiime2/noarch
          package cache : /ebio/abt3_projects/software/dev/miniconda3_dev/pkgs
                          /ebio/abt3/nyoungblut/.conda/pkgs
       envs directories : /ebio/abt3_projects/software/dev/miniconda3_dev/envs
                          /ebio/abt3/nyoungblut/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Linux/4.19.80 ubuntu/18.04.3 glibc/2.27
                UID:GID : 6354:350
             netrc file : None
           offline mode : False
```

I was previously able to install `antismash-5.1.1`. This error is new, probably within the last week or two, suggesting that a dependency is causing the issue, since I think that the `antismash-5.1.1` build is months old now.

**Comment by SJShaw** [comment] 2020-03-21 13:36
@nick-youngblut see #246, that's already fixed and just needs conda to update to 5.1.2

**Comment by nick-youngblut** [comment] 2020-03-21 13:54
Thanks @SJShaw! Do you know if @apcamargo or someone else is working on the PR for 5.1.2? The [last PR](https://github.com/bioconda/bioconda-recipes/pull/20077) seemed to be a lot of work. Hopefully, it will be much easier for 5.1.2

**Comment by kblin** [comment] 2020-03-21 19:27
This one should be easier, as all of the dependencies should be set up already

**Comment by apcamargo** [comment] 2020-03-21 21:42
I've created the PR. In case someone wants to take a look: https://github.com/bioconda/bioconda-recipes/pull/21017

**Comment by etotheten** [comment] 2020-06-25 22:56
I am getting this error when trying to update to `antismash-5.1.2` through bioconda. I was previously able to install 5.1.1, even 5.1.2 with no issue.

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'bioconda::antismash-5.1.2-py_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-5.1.2-py_0
location of failed script: /home/ethan/miniconda3/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/ethan/miniconda3/envs/antismash/lib/python3.7/site-packages/helperlibs/bio/seqio.py", line 21, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ethan/miniconda3/envs/antismash/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/home/ethan/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/ethan/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 31, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/home/ethan/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/record_processing.py", line 16, in <module>
    from helperlibs.bio import seqio
  File "/home/ethan/miniconda3/envs/antismash/lib/python3.7/site-packages/helperlibs/bio/seqio.py", line 23, in <module>
    from Bio._py3k import StringIO
ModuleNotFoundError: No module named 'Bio._py3k'

return code: 1

()
```

**Comment by mswyers** [comment] 2020-06-27 19:00
Also getting an identical error to etotheten trying to install via conda.

**Comment by apcamargo** [comment] 2020-06-27 19:07
Did you try to install it in a clean environment?

**Comment by mswyers** [comment] 2020-06-27 19:09
Yes, this was after completely removing the old antismash environment and installing from scratch.

**Comment by jaybake5** [comment] 2020-06-28 23:54
Also getting the error reported by @etotheten, on an attempted clean install.

**Comment by nextgenusfs** [comment] 2020-06-29 23:00
Same error.  Looks like the post link is to download and setup databases.  Some of us have proxy issues with downloads and have to do this somewhat manually.  I think would be better to have an option to skip the post-link, ie downloading of databases.

**Comment by nextgenusfs** [comment] 2020-06-29 23:27
The workaround for me was to do the following to install v5.1.2
```
conda create -n antismash5 "python>3" pip numpy "biopython=1.76" \
    helperlibs jinja2 pysvg-py3 bcbio-gff pyscss matplotlib scipy "scikit-learn>=0.19" \
    "diamond==0.9.*" "fasttree==2.1.*" "glimmerhmm==3.0.*" hmmer2 \
    "hmmer==3.1b2" "meme<=4.11.2" "muscle==3.8.*" "blast=2.2.*" prodigal
```
And then move into environment, `conda activate antismash5`.

You can then install antismash5 with pip.
```
python -m pip install git+https://github.com/antismash/antismash.git@5-1-2
```
Then you'll have to figure out why the download was failing -- I know why it fails for me which is the proxy settings on our server.  So I will download the resources with `wget` manually where I have control over the proxy settings, for me python requests module I can never configure the proxy settings correctly to get it to work.

**Comment by SJShaw** [comment] 2020-06-30 13:14
For the `ModuleNotFoundError: No module named 'Bio._py3k'` issue, see [here](https://github.com/antismash/antismash/issues/274#issuecomment-651766041).

**Comment by mswyers** [comment] 2020-06-30 15:15
Confirmed that Jon's workaround fixed it for me.

**Comment by SJShaw** [comment] 2020-08-24 13:02
Since only one of the warnings listed is now relevant, I'm going to close this issue and leave the newer issue (#285) specific to that warning open instead.

**Closed by SJShaw** 2020-08-24 13:02 UTC
Labels: conda
