### ISSUE TITLE
antismash.detection.cassis error

### ISSUE THREAD

**Issue by syliang2019** [antismash/antismash#178] opened 2019-06-21 02:08 UTC
**Describe the bug**
Encountered the following error messages when running antiSMASH 5.0.0 from docker image with the option of --cassis. 
antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'meme'
antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'fimo'

**To Reproduce**
/home/antismash/bin/run_antismash ~/data/maker/pcocy/SPAdes_Pcocy_lophfium_scaffolds.fasta ~/data/maker/pcocy/test  --taxon fungi --cassis --tta-threshold 0.65 --cb-general --cb-subclusters --cb-knownclusters --smcog-trees  --fullhmmer --asf --pfam2go --cf-create-clusters --genefinding-tool none --genefinding-gff3 /input/pcocy.all.functional.ipr.sprot.gff  

**System (please complete the following information):**
 - OS: Ubuntu

**Comment by SJShaw** [comment] 2019-06-21 14:06
This is a duplicate of #169.

**Closed by SJShaw** 2019-06-21 14:06 UTC
