### ISSUE TITLE
Error in Lassopeptide detection code

### ISSUE THREAD

**Issue by zachcp** [antismash/antismash#146] opened 2019-05-06 18:58 UTC
**Describe the bug**
Running bacterial genomes in AS5 -RC1 results in unexpected termination due to a bug in the lassopeptide prediction code. 

**Expected behavior**

**To Reproduce**

Reproducible example here:
```bash

# get an example gbk and a script to run docker with the latest tagged release
wget -O bgc.gbk https://mibig.secondarymetabolites.org/repository/BGC0001307/BGC0001307.1.final.gbk
wget https://gist.githubusercontent.com/zachcp/7b5fa4286a5e6f3b08fe638bac4cc5fb/raw/76f6f3ff5e2b7ca9f6b612a54508062a5e1f5080/run_as5rc1.sh

# convert to fasta and run with gene finding
seqmagick convert bgc.gbk bgc.fasta
bash run_as5rc1.sh bgc.fasta .  --genefinding-tool prodigal

```

Error Message Below
```bash
○ → bash run_as5rc1.sh bgc.fasta .  --genefinding-tool prodigal
Traceback (most recent call last):
  File "/usr/local/bin/antismash", line 11, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 120, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 109, in main
    antismash.run_antismash(sequence, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 572, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 637, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 263, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 235, in run_module
    results = module.run_on_record(record, results, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/lassopeptides/__init__.py", line 75, in run_on_record
    return specific_analysis(record)
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/lassopeptides/specific_analysis.py", line 716, in specific_analysis
    motif = run_lassopred(record, cluster, candidate)
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/lassopeptides/specific_analysis.py", line 644, in run_lassopred
    result = determine_precursor_peptide_candidate(record, cluster, query, query.translation)
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/lassopeptides/specific_analysis.py", line 630, in determine_precursor_peptide_candidate
    valid, rodeo_score = run_rodeo(record, cluster, query, query_sequence[:end], query_sequence[end:])
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/lassopeptides/specific_analysis.py", line 596, in run_rodeo
    fimo_motifs, motif_score, fimo_scores = identify_lasso_motifs(leader, core)
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/lassopeptides/specific_analysis.py", line 423, in identify_lasso_motifs
    fimo_output = subprocessing.run_fimo_simple(motif_file, tempfile.name)
  File "/usr/local/lib/python3.5/dist-packages/antismash/common/subprocessing.py", line 299, in run_fimo_simple
    result = execute(command)
  File "/usr/local/lib/python3.5/dist-packages/antismash/common/subprocessing.py", line 91, in execute
    proc = Popen(commands, stdin=stdin_redir, stdout=stdout, stderr=stderr)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
Running antiSMASH FAILED
```

**System (please complete the following information):**
docker AS5 release

**Additional context**
Reproducible example in docker with public data attached above.

**Comment by kblin** [comment] 2019-05-06 19:01
Hi there, this might be a configuration issue in the config file provided in the docker container. I'll follow up on that i a bit.

**Comment by kblin** [comment] 2019-05-06 19:10
I can reproduce this on my machine, and it indeed is because antiSMASH expects FIMO to be around for the RODEO analysis of lassopeptides, and the standalone Docker image doesn't contain that binary because it's not Open Source software.

As a workaround, you can run the container providing the `--without-fimo` parameter. I'll update the container image to always set this flag.

**Comment by kblin** [comment] 2019-05-06 19:14
I guess we should also check the presence of FIMO during our requirement check phase if we expect it to be present. That would make the error message clearer. Any thoughts @SJShaw ?

**Comment by kblin** [comment] 2019-05-06 19:17
Hm, actually we do seem to check, not sure why that didn't fail earlier.

**Comment by zachcp** [comment] 2019-05-06 19:47
Thanks Kai. Please  let me know if I can be of assistance. Great job with AS5 BTW (this bug not withstanding)

**Comment by SJShaw** [comment] 2019-05-06 19:56
From what I can see, https://github.com/antismash/antismash/blob/master/antismash/modules/lassopeptides/specific_analysis.py#L594 should be changed to check `options.executables.fimo` instead, then it should be skipped as expected when FIMO isn't available. It will also let us dump all the `local_config` business for the RiPP modules if we make this change for all of them.

**Comment by kblin** [comment] 2019-05-06 20:15
Fixed in the current `antismash/standalone` and `antismash/standalone-lite` containers.

**Closed by kblin** 2019-05-06 20:15 UTC
Labels: bug
