### ISSUE TITLE
contigs renamed for unknown reason

### ISSUE THREAD

**Issue by kcamnairb** [antismash/antismash#266] opened 2020-05-28 16:40 UTC
I have ran several similarly formatted genbank files on the fungal antismash website, and for some genomes, the contigs are renamed, and others with very similar names are not renamed. I can't figure out why antismash is renaming the contigs. It throws off downstream analysis when I have to figure out what the original name was.

Here is an example of a contig that was renamed:
c00001_Flavus2.. (original name was: Flavus23_contig_1) (Flavus23) 
And here is a contig that was not renamed:
Flavus6_contig_2 (Flavus6)

Is there a way I can keep contigs from being renamed?
Thanks,
Brian

**Comment by SJShaw** [comment] 2020-05-28 19:04
That name is too long for a genbank output, so it's renamed to be shorter.

This is essentially a duplicate of #217, and is handled by #256, so once antiSMASH 5.2 is released you'll be able to use `--allow-long-headers` on the command line if you don't mind the genbanks having issues. In the meantime, you can make the names shorter (e.g. removing the `(Flavus6)` in the name that seems to be redundant).

**Closed by SJShaw** 2020-05-28 19:04 UTC
Labels: duplicate
